### ISSUE TITLE
Unsupported file type

### ISSUE THREAD

**Issue by benknight135** [runestubbe/Crinkler#1]
Whenever I try to use Crinkler I get the following error message:

```
C:\CODE\SML\EXAMPLE\4K.OBJ: error LNK: Unsupported file type
```

I am running an example from [this repository](https://github.com/Beluki/4k-Example) that should work with no trouble. 
Please tell me what I am doing wrong. Everything I am reading is telling me the following command should work:
```
cl /c /W4 /O1 /Os /GS- 4k.cpp

crinkler /ENTRY:EntryPoint  ^
         /SUBSYSTEM:windows ^
         /COMPMODE:SLOW     ^
         /HASHSIZE:100      ^
         /UNSAFEIMPORT      ^
         /OUT:4k.exe        ^
         4k.obj gdi32.lib kernel32.lib user32.lib winmm.lib
```

I am on a 64bit machine on Windows 10

**Comment by askeksa** [comment]
My guess is you are using the compiler for x64. If you just run `cl` on its own, what does it say?

**Comment by runestubbe** [comment]
It seems like Crinkler doesn't recognize the obj file format. I just tried downloading that example, adding Crinkler to the Source folder and running msvc-build-crinkler.bat from the visual studio command line prompt (x86 Native Tools Command Prompt for VS 2019" in the start menu) and it works just fine.

Crinkler doesn't support x64. My best guess is that you might be compiling with the x64 compiler. Can you try running it from the x86 command prompt?

**Comment by benknight135** [comment]
You are correct, I was running from x64 Native Tools Command Prompt for VS 2019. Is there plans to support x64? 
It works great in x84, this is an awesome package.

**Comment by runestubbe** [comment]
Good to hear. We have no current plans for x64 support. For the use case we are targeting (<=8kb intros), x64 is still not that compelling.
