### ISSUE TITLE
[Feature Request] /STUB option

### ISSUE THREAD

**Issue by El-Virus** [runestubbe/Crinkler#3]
I was going to use this linker to build a program with a custom stub, but I have noticed there's no STUB option, would it be possible to add one?

**Comment by runestubbe** [comment]
Assuming you are referring to DOS stubs that is not very likely to happen.
To produce the smallest possible binaries Crinkler executables reclaim the space ordinarily used for the DOS header/stub and use it to store parts of the PE header and decompression code instead. Our goal is to produce the smallest possible windows executables, while staying compatible with all recent windows versions. DOS compatibility is not a priority for us, especially when it comes at the cost of a larger windows binary and more maintenance work. 

If you need a custom, or even just a valid, DOS stub, Crinkler is probably not the tool for you.

**Comment by El-Virus** [comment]
Got the message.
