### ISSUE TITLE
Crinkler23.zip resource flagged as trojan by Windows Defender

### ISSUE THREAD

**Issue by Adobe-Android** [runestubbe/Crinkler#4]
I imagine this is a mistake, but this should be looked into.
https://github.com/runestubbe/Crinkler/releases/tag/v2.3

**Comment by askeksa** [comment]
Thanks for the heads-up.

The detection seems to be fluctuating, sometimes categorizing only the 32-bit version, sometimes both, and sometimes none of them. And it changes which trojan(s) they are categorized as. My guess is there is some extra validation and de-categorization going on behind the scenes.

We will keep an eye on it, and if it looks like it stabilizes on a particular trojan, we will file a false positive report.

**Comment by askeksa** [comment]
I submitted the 32-bit build (which was consistently being flagged) as a false positive, and it was quickly de-flagged.

If the problem reappears, please re-open the issue.
