### ISSUE TITLE
Any interest in CMake

### ISSUE THREAD

**Issue by vsariola** [runestubbe/Crinkler#7]
Hi Rune,

Would you be interested in migrating to CMakeLists.txt instead of .vcxproj for builds? This would be the first step towards porting Crinkler to other platforms, or at least supporting other compilers than Microsoft (e.g. MinGW). Visual Studio users would not have to worry as: 
- Visual Studio 2019 has a good support for CMake projects
- CMake supports nasm / yasm out of the box
- CMake could generate Visual Studio solution / project files if you really really need them.

Any thoughts? I can have a shot at this if you want.

**Comment by runestubbe** [comment]
Hi, I thank you for the offer, but we don't currently have any plans to port Crinkler to other platforms.
