### ISSUE TITLE
Handling the edge case of interval_size == 0x80000000

### ISSUE THREAD

**Issue by vsariola** [runestubbe/Crinkler#8]
Hi,

I think there's a "practically never to expected" corner case how the arithmetic coding is ended:

https://github.com/runestubbe/Crinkler/blob/a947ae4af1e5b817065bea3bb8672d8ff76ef3f9/source/Compressor/AritCode.cpp#L80

Namely, I believe that if interval_size == 0x80000000 and interval_min == 0, then one should skip the ending altogether, as appending a 1 would get you _halfway_ of the interval, but with interval_min == 0 and interval_size == 0x80000000, the half-way point is not included.

I think also interval_size == 0x80000000 and interval_min > 0 should be handled somehow differently.

I don't know how much thermal cooling of the universe would have to take place for this to occur in practice :) But I was reimplementing arithmetic coding and ran into this when my probabilities were getting messed up and got into the point that interval_size = 1, which got scaled to 0x80000000.

**Comment by sagacity** [comment]
I just ran into the same issue when debugging my own coder. You'll find this corner case if you encode a file with a constant 0.5 probability, for instance.

**Comment by askeksa** [comment]
Thanks for the report. The encoding can be skipped whenever `interval_min == 0`, no matter what `interval_size` is. There was also a bug for the case `interval_min == 0x80000000` and `interval_size == 0x80000000`, where the bit was encoded in the wrong position.
